### ISSUE TITLE
Responsive checken

### ISSUE THREAD

**Issue by DivaniNL** [DivaniNL/squad-page#13]

**Comment by ColindeGroot** [comment]
**Homepage:**
slider op grote mobiel niet repsosinve > 1 slide zichtbaar maken
pijlen van de slider passen niet op mobiel wat voor een horizontale scroll zorgt > slider kleiner maken

**Campus**
rechts een groot witte vlak te zien op desktop. Geef andere klas mee an grid container.
tekst in grid items lopen over elkaar heen . opniuew bouwen met flexbox? anders grid beter instellen
algemene kleuren en styling moet nog toegepast worden.

**Detailpagina**
foto's laden niet in of zijn niet goed gestyled . vaste waardes en object fit gebruiken voor betere kwailiteit/verhouding voor foto
table net te klein op tablet formaat > link met route beschrijving staat er te dicht bij op
